### PR TITLE
Remove local cancellation from ABORT TASK path and add simple test

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by sitsofe** [comment]
A variant of test_get_clock_sec already exists in https://github.com/sahlberg/libiscsi/blob/master/utils/iscsi-perf.c . Perhaps the two could be unified somewhere?

**Comment by ddiss** [comment]
Yeah, I saw that but figured that it's small enough not to bother. I can move it somewhere common if you'd prefer - iscsi.h seems a little to public... any suggestions?

**Comment by sitsofe** [comment]
How about iscsi-private.h ? Failing that perhaps there needs to be an iscsi-util.h to collect this style of function that could be useful across test tools and utility tools...

**Comment by sahlberg** [comment]
Merged. thanks

**Pull request merged**
