### PR TITLE
Fix 2 CHAP related issues

### PR DESCRIPTION
**Pull request by cardamon**
Hi!

This fixes two CHAP related issues that arise when using FreeNAS. The first is #189 .

#189 is caused by only reading and hashing the first 255 bytes of the CHAP challange.

From https://tools.ietf.org/html/rfc3720#section-11.1.4 :
> ...and C and R are large-binary-values and their binary length (not the length of the character string that represents them in encoded form) MUST not exceed 1024 bytes.

So a target may send a 2K hex string encoding 1K data...

The second issue is FreeNAS not being very lenient when sending too many headers; FreeNAS will immediately close the connection and log an error:
```
Mar 25 10:05:50 freenas ctld[98731]: 192.168.8.156 (iqn.2007-10.com.github:sahlberg:libiscsi:iscsi-inq): initiator resent InitiatorName
Mar 25 10:05:50 freenas ctld[1993]: child process 98731 terminated with exit status 1
```

I've ran `test_1000_chap.sh` and it still works, so `tgt` support is not affected.

### CODE REVIEW

**Comment by sahlberg** [comment]
I merged it manually after squashing the first three patches into a single patch.

Thanks!

**Comment by mallilinux1980** [comment]
Hi,

May I know which version has this fixed?

Also much appreciated if anyone can give steps to send invalid cmdSN to iscsi target? Ideally as per iscsi RFC target should just ignore or reject I believe? Target should not become unresponsive.

**Comment by sahlberg** [comment]
On Fri, Sep 27, 2019 at 8:53 AM mallilinux1980 <notifications@github.com>
wrote:

> Hi,
>
> May I know which version has this fixed?
>
This should be fixed in version 1.16 and later.

Also much appreciated if anyone can give steps to send invalid cmdSN to
> iscsi target? Ideally as per iscsi RFC target should just ignore or reject
> I believe? Target should not become unresponsive.
>
Look in the test-tool directory.
There are a bunch of tests in there that send invalid PDUs to the target,
such as cmd sequence numbers outside of the allowed window etc
See for example test_iscsi_cmdsn_toohigh.c  which is a test for what the
target does if the cmdsn is too high.  i.e. a test for invalid cmdsn

Also look at the recent commits in the master branch from David Disseldorp
which adds a few more tests like this.

**Comment by sahlberg** [comment]
Oh,
and if you create new scsi/iscsi tests,   please add them to the test-suite
in libiscsi/test-tool instead of writing a new/different test tool.

**Comment by mallilinux1980** [comment]
I tried by downloading a new version 1.19 from gitlab but still say
authorization issue.

The error screenshot is attached for reference. I've also tried target
discovery with given an initiator which is CHAP disabled without
credentials even then i get the same authorization issue.

I don't have problems whatsoever if I use plain iscsiadm commands.

**Comment by mallilinux1980** [comment]
BTW, my OS is RHEL 6.7

**Comment by mallilinux1980** [comment]
i've tried older version 1.7 using RPMs (libiscsi & libiscsi-utils) which
is part of RHEL6 distribution after I disable CHAP UN & PW forgiven a host
IQN (aka initiator) I find no authorization issues but test is aborted with
glibc memory backtrace. Attached screenshot for reference.

**Pull request closed without merging**
